import "./globals.css";
import { Inter, Mandali } from "next/font/google";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Header className={'container'}/>
          <main className={'container'}>{children}</main>
          <Footer className={'container'}/>
      </body>
    </html>
  );
}
